### ISSUE TITLE
Issue #94 was not resolved

### ISSUE THREAD

**Issue by oshybrid** [RailsApps/learn-rails#96] opened 2017-05-12 18:47 UTC
Hey just to let you know after i did what you suggested it didn't fix the CCS issue.
Results remain the same.

Current Gems

actioncable (5.1.0, 5.0.2)
actionmailer (5.1.0, 5.0.2)
actionpack (5.1.0, 5.0.2)
actionview (5.1.0, 5.0.2)
activejob (5.1.0, 5.0.2)
activemodel (5.1.0, 5.0.2)
activerecord (5.1.0, 5.0.2)
activesupport (5.1.0, 5.0.2, 2.3.14)
addressable (2.5.1)
arel (8.0.0, 7.1.4)
aruba (0.14.2)
autoprefixer-rails (6.7.7.2)
background_process (1.3)
bcat (0.6.2)
better_errors (2.1.1)
bigdecimal (1.3.0)
bindex (0.5.0)
bootstrap-sass (3.3.7)
builder (3.2.3)
bundler (1.14.6)
bundler-unload (1.0.2)
byebug (9.0.6)
capybara (2.13.0)
childprocess (0.6.3, 0.5.9)
cleaner (0.0.7)
coderay (1.1.1)
coffee-rails (4.2.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5)
contracts (0.15.0)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-rails (1.4.5)
cucumber-wire (0.0.1)
daemons (1.2.4)
database (0.0.0)
database_cleaner (1.5.3)
debase (0.2.2.beta9)
debase-ruby_core_source (0.9.9)
did_you_mean (1.1.0)
diff-lcs (1.3)
erubi (1.6.0)
erubis (2.7.0)
execjs (2.7.0)
executable-hooks (1.3.2)
factory_girl (4.8.0)
faraday (0.12.1)
ffi (1.9.18)
filelist (0.0.1)
gem-wrappers (1.2.7)
gherkin (4.1.1)
gibbon (3.0.1)
globalid (0.4.0)
high_voltage (3.0.0)
httparty (0.14.0)
i18n (0.8.1)
io-console (0.4.6)
jbuilder (2.6.3)
jquery-rails (4.3.1)
json (2.0.3, 2.0.2)
launchy (2.4.3)
listen (3.0.8)
loofah (2.0.3)
mail (2.6.5, 2.6.4)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.10.2, 5.10.1)
multi_json (1.12.1)
multi_test (0.1.2)
multi_xml (0.6.0)
multipart-post (2.0.0)
net-telnet (0.1.1)
nio4r (2.0.0)
nokogiri (1.7.2, 1.7.1)
openssl (2.0.3)
power_assert (0.4.1)
pry (0.10.4)
psych (2.2.2)
public_suffix (2.0.5)
puma (3.8.2)
rack (2.0.2, 2.0.1, 1.6.5)
rack-protection (1.5.3)
rack-test (0.6.3)
rails (5.1.0, 5.0.2)
rails-dom-testing (2.0.2)
rails-html-sanitizer (1.0.3)
rails_layout (1.0.40)
railties (5.1.0, 5.0.2)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (5.0.0)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-rails (3.5.2)
rspec-support (3.5.0)
ruby-debug-ide (0.6.1.beta4)
rubygems-bundler (1.4.4)
rubygems-update (2.6.1)
rvm (1.11.3.9)
sass (3.4.23)
sass-rails (5.0.6)
service_manager (0.6.4)
simple_form (3.4.0)
sinatra (1.4.8)
slop (3.6.0)
spring (2.0.1)
spring-watcher-listen (2.0.1)
sprockets (3.7.1)
sprockets-rails (3.2.0)
sqlite3 (1.3.13)
tcpsocket-wait (1.0.0)
test-unit (3.2.3)
thor (0.19.4)
thread_safe (0.3.6)
tilt (2.0.7)
turbolinks (5.0.1)
turbolinks-source (5.0.3, 5.0.0)
typescript-node (1.6.2)
typescript-rails (0.6.2.4)
typescript-src (1.6.2.0)
tzinfo (1.2.3)
uglifier (3.2.0)
watchr (0.7)
web-console (3.5.0)
websocket-driver (0.6.5)
websocket-extensions (0.1.2)
xmlrpc (0.2.1)
xpath (2.0.0)

**Comment by DanielKehoe** [comment] 2017-05-17 13:17
This is a duplicate of a closed issue.

**Closed by DanielKehoe** 2017-05-17 13:17 UTC
